# Products
components:
  schemas:
    products:
      type: object
      required:
        - id
        - timestamp
        - name
        - category
        - description
        - code
        - price
        - photo
        - stock
      properties:
        id:
          type: string
          description: Identificador autogenerado por MongoDB de cada Producto
        timestamp:
          type: string
          description: Momento en el cual se cargo el producto
        name:
          type: string
          description: Nompre del producto
        category:
          type: string
          description: Categoria del producto
        description:
          type: string
          description: Descripcion del producto
        code:
          type: string
          description: Codigo del Producto con el que se va a identificar en el E-commerce
        price:
          type: number
          description: Precio del producto
        photo:
          type: string
          description: URL de la Imagen del producto
        stock:
          type: number
          description: Cantidad de productos en stock
      example:
        id: 643df20356e60a82bf2d617d
        timestamp: 1681781251666
        name: Versace
        category: camisas
        description: camisa elegante
        code: CC-AA
        price: 300
        photo: img.jpg
        stock: 100